VERILOG=/home/course/comporg/bin/ncverilog
VERILOG_SOURCE=test_sevenseg.v \
../rtl/PICO16a_system.v \
../rtl/util_register_1bit.v \
../rtl/util_register.v \
../rtl/memory.v \
../rtl/memory_lpm.v \
../rtl/pico16a.v \
../rtl/util_genClk.v \
../rtl/sevenseg_dec.v \
../rtl/adrs_dec_7seg.v \
../rtl/dev_cnt_7seg.v \
../rtl/dev_interface_7seg.v \
/usr/local/quartus-12.0/quartus/eda/sim_lib/altera_mf.v
LANG = C
LC_ALL = C

VL_OPT=
VIEWER=/home/course/comporg/bin/simvision
PERL=perl /home/course/comporg/bin/pasm.pl

sim:    perl-sim simulation viewer

perl-sim:
	$(PERL) -v sample_sevenseg.s

perl-fpga:
	$(PERL) -m sample_sevenseg.s

simulation:
		rm -rf INCA_libs test_sevenseg result_sevenseg.txt
	$(VERILOG) $(VERILOG_SOURCE) $(VL_OPT) 

viewer:
	$(VIEWER) -input simvision.svcf


clean:
	rm -rf *~ INCA_libs test_sevenseg result_sevenseg.txt sample_sevenseg.mem sample_sevenseg.mif 
